### PR TITLE
feat(create_attribute): support object

### LINKED ISSUE #6: TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
Hello,

First of all, thanks for your work :slightly_smiling_face: !

When using create_attribute in a template, I get the following error : 

```
      TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))                                                                                                                                                                        
          at new Map (<anonymous>)                                                                                                                                                                                                                            
          at new DrupalAttribute (/usr/src/app/www/web/node_modules/drupal-attribute/src/index.js:3:5)                                                                                                                                                        
          at Twig.Template.<anonymous> (/usr/src/app/www/web/node_modules/twig-testing-library/dist/index.js:188:22)                                                                                                                                          
          at Twig.Template.parse (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:4362:48)                                                                                                                                 
          at /usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:4780:58
          at Array.forEach (<anonymous>)                                                                                                                                                                                                                      
          at Object.Twig.forEach (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:79:24)                                                                                                                                   
          at Twig.Template.Twig.expression.parse (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:4777:14)
          at Twig.Template.parse (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:2966:51)
          at Twig.Template.Twig.logic.parse (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:3779:43)
          at parseToken (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:768:54)
          at Array.forEach (<anonymous>)                                                                                                                                                                                                                      
          at Object.Twig.forEach (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:79:24)
          at Twig.Template.Twig.parse (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:758:18)
          at Twig.Template.render (/usr/src/app/www/web/themes/contrib/ovh_theme_patternlab/node_modules/twig/twig.js:1195:29)
          at /usr/src/app/www/web/node_modules/twig-testing-library/dist/index.js:230:31

```

The problem seems to be linked to implementation of the function `create_attribute` here : https://github.com/larowlan/twig-testing-library/blob/master/src/index.js#L47

It seems to not support objects, whereas Drupal's documentation states that objects can be passed to `create_attribute` : https://www.drupal.org/docs/8/theming-drupal-8/using-attributes-in-templates#s-create-attributes-in-twig.

I took the liberty to attempt a quick fix on a fork doing something like this : 
```
  Twig.extendFunction("create_attribute", (value) => {
    if (typeof value === 'object' && value !== null) value = Object.entries(value)
    return new DrupalAttribute(value);
  })
```
Here is the link to the corresponding commit : https://github.com/tbourrelovh/twig-testing-library/commit/9073402c029fdf62d8b7e92f5f32001378698c6b

Would it be possible to add such a feature to your code ? I obviously can do a PR if needed :smile:

### PR DESCRIPTION
**Pull request by tbourrelovh**
closes #6

### CODE REVIEW

**Comment by larowlan** [comment]
cheers

**Comment by tbourrelovh** [comment]
Could you please include it in a new release and publish it to npm :slightly_smiling_face: ?

**Comment by larowlan** [comment]
looks like I need to do some work to setup travis-ci.com now that travis-ci.org is gone

**Comment by larowlan** [comment]
I've done the migration, but now I'm getting authorisation issues - will try to debug it in the morning

**Comment by tbourrelovh** [comment]
Okay thanks for the updates

**Comment by larowlan** [comment]
just moved to github actions instead, should be good to go now, thanks for your contributions

**Pull request merged**
