### PR TITLE
Support twig extensions

### LINKED ISSUE #1: Exporting twig for extending its functionality
Hey,

thank you for that cool library! Exporting twig would be really helpful for us, as we use custom functions in our templates. If `twig-testing-library` exported it, we could something like the following:

```
import { render, twig } from "twig-testing-library";

twig.extendFunction("custom_function", () => ...);

describe(...);
```

Thanks,
Michael

### PR DESCRIPTION
**Pull request by larowlan**
Adds an extra argument to `render` that takes a callback that can modify Twig to add additional filters/functions etc.

Fixes #1

### CODE REVIEW

**Comment by larowlan** [comment]
cc @mgrsskls - give this a once-over?

**Comment by mgrsskls** [comment]
Hey @larowlan,

thanks for doing that so quickly! When I checked the lib to see how to do it I thought of simply exporting `Twig` here: https://github.com/larowlan/twig-testing-library/blob/master/src/index.js#L92.
Is there a reason you implemented this using a callback? But anyway, looks good to me!

**Comment by larowlan** [comment]
@mgrsskls at that stage the render call is already complete, so I don't think you've got the ability to use the twig object.

But thinking it about some more, Twig is exported from Twig.js itself, so you can probably import it at the top of your test, or in a beforeEach

**Comment by mgrsskls** [comment]
The export from twig is its render function, extending should happen directly on the import: https://github.com/twigjs/twig.js/wiki/Extending-twig.js

But yes, that is exactly what I thought of:

```
import { render, Twig } from "twig-testing-library";

Twig.extendFunction("some_function", () => "");

it("Should render", async () => {
  const { container } = await render(component, {});
  expect(container).toMatchSnapshot();
});
```

That way the `render` call should not have happened yet.

**Comment by larowlan** [comment]
oh yeah 🤦 doing that now

**Comment by larowlan** [comment]
Pushed that up

**Comment by larowlan** [comment]
if that works for you, let me know and i'll cut a new release

**Comment by mgrsskls** [comment]
Looks good! Also good idea to leave the callback in there, could be useful.

Thank you!

**Comment by larowlan** [comment]
I'll leave the callback out for now, not sure what I was thinking at the time

**Comment by larowlan** [comment]
semantic-release ❤️

**Pull request merged**
